### ISSUE TITLE
Exception when trying to create resources

### ISSUE THREAD

**Issue by dspitzer** [Twingate-Labs/pulumi-twingate#4]
Unfortunately the plugin doesn't seem to work properly yet. I have a Typescript based Pulumi project and trying to use the twingate plugin always results in the following error. I've tried with the current 0.0.14 down to 0.0.9 version of the plugin but it is always the same:

```
Diagnostics:
  pulumi:providers:twingate (default_0_0_9_https_/github.com/Twingate-Labs/pulumi-twingate/releases/download/v__VERSION_):
    error: could not read plugin [/root/.pulumi/plugins/resource-twingate-v0.0.9/pulumi-resource-twingate] stdout: EOF

  pulumi:pulumi:Stack (environments-base-staging):
    panic: strconv.ParseUint: parsing "": invalid syntax
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.GetModuleMajorVersion(0x0, 0x0, 0x400053b9a0, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.21.0/pkg/tfbridge/info.go:760 +0x140
    github.com/Twingate/pulumi-twingate/provider.Provider(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/runner/work/pulumi-twingate/pulumi-twingate/provider/resources.go:105 +0x584
    main.main()
    	/home/runner/work/pulumi-twingate/pulumi-twingate/provider/cmd/pulumi-resource-twingate/main.go:27 +0x28
```

It seems like sth is wrong with the plugin version string.

**Comment by emrul** [comment]
Hi @dspitzer - thanks for reporting this, we will look into it and update shortly.

**Comment by betamike** [comment]
I'm seeing this issue as well. I tested the latest published `pulumi-resource-twingate` binary and it is happening there: 

```
betamike /tmp/test
> curl -LO https://github.com/Twingate-Labs/pulumi-twingate/releases/download/v0.0.14/pulumi-resource-twingate-v0.0.14-linux-amd64.tar.gz && tar xf pulumi-resource-twingate-v0.0.14-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13.9M  100 13.9M    0     0  72.0M      0 --:--:-- --:--:-- --:--:-- 72.0M

betamike /tmp/test
> ll
total 46228
-rw-r--r-- 1 1001    11358 May  6 13:59 LICENSE
-rwxr-xr-x 1 1001 32654859 May  6 14:04 pulumi-resource-twingate
-rw-r--rw- 1 root 14661204 Jun  3 20:52 pulumi-resource-twingate-v0.0.14-linux-amd64.tar.gz
-rw-r--r-- 1 1001     1018 May  6 13:59 README.md

betamike /tmp/test
> ./pulumi-resource-twingate
panic: strconv.ParseUint: parsing "": invalid syntax

goroutine 1 [running]:
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.GetModuleMajorVersion(0x0, 0x0, 0xc0005919b8, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.21.0/pkg/tfbridge/info.go:760 +0x1dc
github.com/Twingate/pulumi-twingate/provider.Provider(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/pulumi-twingate/pulumi-twingate/provider/resources.go:105 +0x635
main.main()
        /home/runner/work/pulumi-twingate/pulumi-twingate/provider/cmd/pulumi-resource-twingate/main.go:27 +0x37
```

My best guess is that somewhere in the release process, `Version` is not being set [here](https://github.com/Twingate-Labs/pulumi-twingate/blob/master/provider/pkg/version/version.go#L18). This empty `Version` string ends up being passed into tfgen [here](https://github.com/Twingate-Labs/pulumi-twingate/blob/master/provider/cmd/pulumi-resource-twingate/main.go#L27), resulting in the semver parser failing down the callstack.

**Comment by emrul** [comment]
Ok, this issue should be fixed in the latest release. Thanks for the pointer @betamike - looks like we had some package naming issues as we were flipping between which GH org this provider would sit in.

The latest release has also been upgraded to the latest Terraform provider version (v0.1.7).
